export const ENDPOINTS = {
  SECURITY: {
    LOGIN: '/security/login',
    VERIFY_2FA: '/security/login/2fa/verify',
    RESEND_2FA: (sessionId: string) => `/security/2fa/resend/${sessionId}`,
    CANCEL_2FA: (sessionId: string) => `/security/2fa/session/${sessionId}`,
    REGISTER: '/security/register',
    PASSWORD_RECOVERY_REQUEST: '/security/password-recovery/request',
    PASSWORD_RECOVERY_CONFIRM: '/security/password-recovery/confirm',
    VALIDATE_TOKEN: '/security/validate-token',
    OAUTH_GOOGLE_URL: '/security/google/url',
    OAUTH_GOOGLE_CODE: '/security/google/code',
    OAUTH_GITHUB_URL: '/security/github/url',
    OAUTH_GITHUB_CODE: '/security/github/code',
    OAUTH_MICROSOFT_URL: '/security/microsoft/url',
    OAUTH_MICROSOFT_CODE: '/security/microsoft/code',
    UNLINK_GOOGLE: (userId: string) => `/security/google/unlink/${userId}`,
    UNLINK_GITHUB: (userId: string) => `/security/github/unlink/${userId}`,
    UNLINK_MICROSOFT: (userId: string) => `/security/microsoft/unlink/${userId}`,
  },
  USERS: {
    BASE: '/users',
    BY_ID: (id: string) => `/users/${id}`,
    SEARCH: (query: string) => `/users/search?q=${encodeURIComponent(query)}`,
    WITH_ROLES: (userId: string) => `/users/${userId}/with-roles`,
    ROLES: (userId: string) => `/users/${userId}/roles`,
    ROLE_BY_ID: (userId: string, roleId: string) => `/users/${userId}/roles/${roleId}`,
    PERMISSIONS: (userId: string) => `/users/${userId}/permissions`,
    COMPLETE_INFO: (userId: string) => `/users/${userId}/complete-info`,
    ADD_PROFILE: (userId: string, profileId: string) => `/users/${userId}/profile/${profileId}`,
    DELETE_PROFILE: (userId: string, profileId: string) => `/users/${userId}/profile/${profileId}`,
    ADD_SESSION: (userId: string, sessionId: string) => `/users/${userId}/session/${sessionId}`,
    DELETE_SESSION: (userId: string, sessionId: string) => `/users/${userId}/session/${sessionId}`,
  },
  PROFILES: {
    BASE: '/profiles',
    BY_ID: (id: string) => `/profiles/${id}`,
  },
  ROLES: {
    BASE: '/roles',
    BY_ID: (id: string) => `/roles/${id}`,
  },
  PERMISSIONS: {
    BASE: '/permissions',
    BY_ID: (id: string) => `/permissions/${id}`,
  },
  SESSIONS: {
    BASE: '/sessions',
    BY_ID: (id: string) => `/sessions/${id}`,
  },
  ROLE_PERMISSIONS: {
    BASE: '/role-permissions',
    BY_ID: (id: string) => `/role-permissions/${id}`,
  },
  USER_ROLE: {
    BASE: '/user-role',
    ASSIGN: (userId: string, roleId: string) => `/user-role/user/${userId}/role/${roleId}`,
    REMOVE: (userRoleId: string) => `/user-role/${userRoleId}`,
    UPDATE_BULK: (userId: string) => `/user-role/user/${userId}`,
  },
  USERS_QUERY: {
    BASE: '/users-query',
  },
  BUSINESS: {
    BOLETO: '/boleto',
    BUS: '/bus',
    CIUDADANO: '/ciudadano',
    CONDUCTOR: '/conductor',
    DESIGNATARIO_GRUPO: '/designatario-grupo',
    DESIGNATARIO_PERSONA: '/designatario-persona',
    DIRECCION: '/direccion',
    EMPRESA: '/empresa',
    FOTO: '/foto',
    GPS: '/gps',
    GRUPO_PERSONA: '/grupo-persona',
    GRUPO: '/grupo',
    HISTORIAL: '/historial',
    INCIDENTE_BUS: '/incidente-bus',
    INCIDENTE: '/incidente',
    MENSAJE: '/mensaje',
    METODO_PAGO_CIUDADANO: '/metodo-pago-ciudadano',
    METODO_PAGO: '/metodo-pago',
    NODO: '/nodo',
    PARADERO: '/paradero',
    PERSONA: '/persona',
    PROGRAMACION: '/programacion',
    RECARGA: '/recarga',
    REPORTES: '/reportes',
    RUTA: '/ruta',
    TURNO: '/turno',
  },
};
